# Generated by Django 2.2.5 on 2019-09-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='Меню')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.IntegerField(verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Меню'),
        ),
    ]
