# Generated by Django 2.2.5 on 2019-09-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190928_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Меню'},
        ),
    ]
