# Generated by Django 2.2.5 on 2019-09-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190928_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='paid', to='app.Product', verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.Product', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена, BYN'),
        ),
    ]
