# Generated by Django 2.2.5 on 2019-09-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190928_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.ForeignKey(default='Product.price', on_delete=django.db.models.deletion.PROTECT, related_name='paid', to='app.Product', verbose_name='Оплачено'),
        ),
    ]
