# Generated by Django 2.2.5 on 2019-09-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190929_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.ForeignKey(default='price', on_delete=django.db.models.deletion.PROTECT, related_name='paid', to='app.Product', verbose_name='Оплачено'),
        ),
    ]
