# Generated by Django 2.2.5 on 2019-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190929_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(verbose_name='Оплачено'),
        ),
    ]
